# Generated by Django 3.2.18 on 2024-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='app_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='apilogsmodel',
            index=models.Index(fields=['app_name'], name='drf_api_log_app_nam_99cb4d_idx'),
        ),
    ]
